FROM golang:alpine3.10

# env
ENV KAFKA_HOST dev.localhost
ENV KAFKA_PORT 9092
ENV KAFKA_TOPIC assignment

WORKDIR /src/golang-kafka/producer
# install dependencies
RUN go get -t -v ./...

# build
RUN go build -o app main.go

ENTRYPOINT ["/src/golang-kafka/producer/app"]